config/routes.rb
Resume::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "welcome/index"

  devise_for :users

root:to=>'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:admin
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
before_filter :authenticate_user!
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrandName</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
      $(function() {
          $(".edit_link").click(function() {
              $.get("<%=params[:controller]%>" + "/" + $(this).attr("id") + "/edit", function(data) {

                  $("#edit_form .modal-body").html(data);
                  $("#edit_form").modal('toggle');
              });
          });
      });
  </script>
  <%= yield(:head) %>
</head>
<body>
<div id="wrapper">
  <div class="navbar navbar-fixed-top" style="z-index: 999999999">
    <div class="navbar-inner" style="z-index: 999999999">
      <div class="container">
        <a class="brand" href="/">BrandName</a>
        <ul class="nav">
          <li><a href="#about" style="color:white;">About</a></li>
          <!--<li><a href="#contact" style="color:white;">Contact</a></li>-->
        </ul>

        <% if !user_signed_in? %>
            <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class =>"pull-right navbar-form"}) do |f| %>
                <%= f.email_field :email, :class=>"input-small", :placeholder=>"Email" %>
                <%= f.password_field :password, :class=>"input-small", :placeholder=>"Password" %>
                <%= f.submit "Sign In", :class=>"primary btn" %>
            <% end %>
        <% else %>
            <div class="pull-right" style="margin-top: 10px;color:white;">
              <%= current_user.email %>
              <span class="nav_link">
              | <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :style=>"color:white;" %>
            </span>
            </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">

    <div class="page-header" style="height:100px"></div>
    <div style="position:absolute;margin-top: -60px;" class="span12">
      <h2>  <%= yield(:page_header) %></h2>
    </div>
  </div>
  <div class="container">

    <div class="content">
      <%= js extend_gritter :position => :bottom_right %>
      <%= js add_gritter(flash[:notice], :image => :success, :title => "Notice", :sticky => false, :time => 2000) %>
      <%= js add_gritter(flash[:alert], :image => :warning, :title => "Alert!", :sticky => false, :time => 2000) %>
      <%= yield %>
    </div>

    <% if request.fullpath=="/" %>



    <% end %>
  </div>
</div>

<%= javascript_include_tag "/assets/exclusions/jquery.pageslide" %>


</body>
</html>

app/views/layouts/scaffold.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrandName</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
      $(function() {
          $(".edit_link").click(function() {
              $.get("<%=params[:controller]%>" + "/" + $(this).attr("id") + "/edit?get=1", function(data) {

                  $("#edit_form .modal-body").html(data);
                  $("#edit_form").modal('toggle');

              });
          });
      });
  </script>
  <%= yield(:head) %>
  <style>
      table td {
          border: none;
      }

      table tr {
          border: none;
      }
  </style>
</head>
<body>
<div id="wrapper">
  <div class="navbar navbar-fixed-top" style="z-index: 999999999">
    <div class="navbar-inner" style="z-index: 999999999">
      <div class="container">
        <a class="brand" href="/">BrandName</a>
        <ul class="nav">
          <li><a href="#about" style="color:white;">About</a></li>
          <!--<li><a href="#contact" style="color:white;">Contact</a></li>-->
        </ul>

        <% if !user_signed_in? %>
            <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class =>"pull-right navbar-form"}) do |f| %>
                <%= f.email_field :email, :class=>"input-small", :placeholder=>"Email" %>
                <%= f.password_field :password, :class=>"input-small", :placeholder=>"Password" %>
                <%= f.submit "Sign In", :class=>"primary btn" %>
            <% end %>
        <% else %>
            <div class="pull-right" style="margin-top: 10px;color:white;">
              <%= current_user.email %>
              <span class="nav_link">
              | <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :style=>"color:white;" %>
            </span>
            </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container">

    <div class="page-header" style="height:100px"></div>
    <div style="position:absolute;margin-top: -110px;" class="span16">
      <%= yield(:page_header) %>
    </div>

    <div class="content">
      <%= js extend_gritter :position => :bottom_right %>
      <%= js add_gritter(flash[:notice], :image => :success, :title => "Notice", :sticky => false, :time => 2000) %>
      <%= js add_gritter(flash[:alert], :image => :warning, :title => "Alert!", :sticky => false, :time => 2000) %>
      <%= yield %>
    </div>

    <% if request.fullpath=="/" %>



    <% end %>
  </div>
</div>

<%= javascript_include_tag "/assets/exclusions/jquery.pageslide" %>


</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>